language: java
jdk:
  - openjdk11

jobs:
  include:
    - arch: amd64
      dist: xenial
    - arch: amd64
      dist: bionic
    - arch: ppc64le
      dist: xenial
    - arch: ppc64le
      dist: bionic
