language: java
jdk:
  - openjdk8

jobs:
  include:
    - arch: amd64
      dist: xenial
    - arch: amd64
      dist: bionic
    - arch: ppc64le
      dist: xenial
    - arch: ppc64le
      dist: bionic
      
before_install: echo $JAVA_HOME      
